// <auto-generated />
using System;
using System.Collections.Generic;
using GainIt.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GainIt.API.Migrations
{
    [DbContext(typeof(GainItDbContext))]
    [Migration("20250403123003_AddAnnotationsToModels")]
    partial class AddAnnotationsToModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GainIt.API.Models.Projects.Project", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedMentorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DifficultyLevel")
                        .HasColumnType("integer");

                    b.Property<Guid?>("OwningOrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProjectDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProjectSource")
                        .HasColumnType("integer");

                    b.Property<int>("ProjectStatus")
                        .HasColumnType("integer");

                    b.Property<string>("RepositoryLink")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<Guid>>("TeamMemberIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.PrimitiveCollection<List<string>>("TechnologyStack")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("ProjectId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("GainIt.API.Models.Users.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserRole")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("GainIt.API.Models.Users.Gainers.Gainer", b =>
                {
                    b.HasBaseType("GainIt.API.Models.Users.User");

                    b.PrimitiveCollection<List<string>>("AreasOfInterest")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("EducationStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("Gainers");
                });

            modelBuilder.Entity("GainIt.API.Models.Users.Mentors.Mentor", b =>
                {
                    b.HasBaseType("GainIt.API.Models.Users.User");

                    b.Property<string>("AreaOfExpertise")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("integer");

                    b.ToTable("Mentors");
                });

            modelBuilder.Entity("GainIt.API.Models.Users.Nonprofits.NonprofitOrganization", b =>
                {
                    b.HasBaseType("GainIt.API.Models.Users.User");

                    b.Property<string>("WebsiteUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("Nonprofits");
                });

            modelBuilder.Entity("GainIt.API.Models.Users.Gainers.Gainer", b =>
                {
                    b.HasOne("GainIt.API.Models.Users.User", null)
                        .WithOne()
                        .HasForeignKey("GainIt.API.Models.Users.Gainers.Gainer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GainIt.API.Models.Users.Mentors.Mentor", b =>
                {
                    b.HasOne("GainIt.API.Models.Users.User", null)
                        .WithOne()
                        .HasForeignKey("GainIt.API.Models.Users.Mentors.Mentor", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GainIt.API.Models.Users.Nonprofits.NonprofitOrganization", b =>
                {
                    b.HasOne("GainIt.API.Models.Users.User", null)
                        .WithOne()
                        .HasForeignKey("GainIt.API.Models.Users.Nonprofits.NonprofitOrganization", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
