# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - GainItWebApp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build with dotnet
        run: dotnet build backend/GainIt/GainIt.API/GainIt.API.csproj --configuration Release


      - name: dotnet publish
        run: dotnet publish backend/GainIt/GainIt.API/GainIt.API.csproj -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Install Sysinternals Strings
        shell: pwsh
        run: choco install sysinternals -y

      - name: Verify built DLL contains new auth marker
        shell: pwsh
        run: |
          $dll = "${{env.DOTNET_ROOT}}/myapp/GainIt.API.dll"
          Write-Host "Checking DLL for marker: $dll"
          $stringsExe = "C:\\ProgramData\\chocolatey\\lib\\sysinternals\\tools\\strings.exe"
          if (-not (Test-Path $stringsExe)) { Write-Error "strings.exe not found at $stringsExe"; exit 1 }
          $hasMarker = & $stringsExe $dll | Select-String "AUTH CONFIG VERSION v3" -Quiet
          if (-not $hasMarker) { Write-Error "AUTH CONFIG VERSION v3 marker NOT found in GainIt.API.dll"; exit 1 }
          Write-Host "Marker found. Proceeding."

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ./artifact
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_51F2AFA3F65240F99DB839FFBC48CD03 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_92BD9DB22FC94ED48B7EEDD63CEC6104 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_80FCFF36DC004C80A212158594C35A58 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'GainItWebApp'
          slot-name: 'Production'
          package: ./artifact
          clean: true
          
